baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en-us"
title = "GDPR observer"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]

  [params.homepage]
    show_contact_box = false # show / hide the contaxt box on the homepage
    show_services_button = false # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    mobile_height = "36px"
    desktop = "images/logo/gdpr-observer-logo-v1.png"
    desktop_height = "36px"
    alt = "GDPR observer"

  [params.colors]
    primary = "#ff1fff"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
    meta_twitter_site = "@hermescenter"
    meta_twitter_creator = "@hermescenter"
    meta_og_image = "https://www.ffwd.org/wp-content/uploads/0f2987d.png"

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Supporting European DPOs in get rid of Google & Co; <a class="zerostatic" href="https://hermescenter.org">Hermes Center</a>.'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Backstory"
    url = "/backstory/"
    weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Technical logs"
    url = "/logs/"
    weight = 1

  [[menu.footer]]
    name = "Meet the team"
    url = "/team/"
    weight = 2
